<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <IsPackable>false</IsPackable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Octelys.MediatorPlugin.Tests</RootNamespace>
        <AssemblyName>Octelys.MediatorPlugin.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.ReSharper.SDK.Tests" Version="$(SdkVersion)" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="GitHubActionsTestLogger" Version="2.4.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="test/**/*" />
        <None Include="test/**/*" />
        <None Remove="Packages\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MediatorPlugin\MediatorPlugin.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="test\data\TestSolution\Entities\" />
      <Folder Include="test\data\TestSolution\Mediator\Handlers\" />
      <Folder Include="test\data\TestSolution\Mediator\Notifications\" />
      <Folder Include="test\data\TestSolution\Mediator\Requests\" />
      <Folder Include="test\data\TestSolution\MediatR\Handlers\" />
      <Folder Include="test\data\TestSolution\MediatR\Notifications\" />
      <Folder Include="test\data\TestSolution\MediatR\Requests\" />
    </ItemGroup>
</Project>
